version: '3.8'

services:
  nacos-server:
    image: nacos/nacos-server:v2.2.3
    container_name: nacos-server
    restart: always
    environment:
      - MODE=standalone  # 单机模式也可连接外部MySQL
      - SPRING_DATASOURCE_PLATFORM=mysql  # 指定使用MySQL
      - MYSQL_SERVICE_HOST=mysql  # MySQL容器名（需与docker-compose中一致）
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=nacos_config  # 数据库名（需预先创建）
      - MYSQL_SERVICE_USER=root  # MySQL用户名
      - MYSQL_SERVICE_PASSWORD=root  # 与MySQL配置一致
      - MYSQL_DATABASE_NUM=1  # 数据库实例数量
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    ports:
      - "8848:8848"
    volumes:
      - nacos-data:/home/nacos/data
      - nacos-log:/home/nacos/logs
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8848/nacos/actuator/health"]  # 检查nacos健康接口
      interval: 10s
      timeout: 5s
      retries: 10  # 增加重试次数，确保nacos完全启动

# MySQL 服务（统一初始化3个数据库）
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root  # 数据库密码（与脚本中一致）
      - MYSQL_CHARSET=utf8mb4     # 默认字符集（避免中文乱码）
      - TZ=Asia/Shanghai          # 时区配置（与系统一致）
    ports:
      - "3306:3306"
    volumes:
      # 1. 先执行：初始化uaa_db、product_db、nacos_config库
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      # 3. 数据持久化卷（避免容器删除后数据丢失）
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    # 健康检查：确保MySQL完全就绪后再启动其他服务
    healthcheck:
      test: |
        mysql -uroot -proot -e "USE nacos_config; SHOW TABLES LIKE 'config_info';" | grep -q 'config_info'
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  openldap:
    image: osixia/openldap:1.4.0
    container_name: openldap
    environment:
      - LDAP_ORGANISATION=Example
      - LDAP_DOMAIN=example.com
      - LDAP_ADMIN_PASSWORD=admin
    ports:
      - "389:389"
    volumes:
      - ./ldap-init/:/container/service/slapd/assets/config/bootstrap/ldif/custom/
      - ldap-data:/var/lib/ldap
      - ldap-config:/etc/ldap/slapd.d
    networks:
      - app-network

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
    ports:
      - "6443:443"
    depends_on:
      - openldap
    networks:
      - app-network

  uaa-service:
    build:
      context: ./uaa-service
      dockerfile: Dockerfile
    container_name: uaa-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/uaa_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_LDAP_URLS=ldap://openldap:389
      - SPRING_LDAP_BASE=dc=example,dc=com
      - SPRING_LDAP_USERNAME=cn=admin,dc=example,dc=com
      - SPRING_LDAP_PASSWORD=admin
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER-ADDR=nacos-server:8848
      - SPRING_CLOUD_NACOS_CONFIG_SERVER-ADDR=nacos-server:8848
      - SECURITY_OAUTH2_RESOURCE-SERVER_JWT_SECRET=your-jwt-secret-key
    ports:
      - "8081:8081"
    depends_on:
      nacos-server:
        condition: service_healthy  # 等待nacos-server健康检查通过
      mysql:
        condition: service_healthy  # 等待mysql健康检查通过
    networks:
      - app-network

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    container_name: product-service
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/product_db?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER-ADDR=nacos-server:8848
      - SPRING_CLOUD_NACOS_CONFIG_SERVER-ADDR=nacos-server:8848
      - SECURITY_OAUTH2_RESOURCE-SERVER_JWT_SECRET=your-jwt-secret-key
    ports:
      - "8082:8082"
    depends_on:
      nacos-server:
        condition: service_healthy
      mysql:
        condition: service_healthy
      uaa-service:
        condition: service_started
    networks:
      - app-network

  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    container_name: gateway-service
    environment:
      - SPRING_CLOUD_NACOS_DISCOVERY_SERVER-ADDR=nacos-server:8848
      - SPRING_CLOUD_NACOS_CONFIG_SERVER-ADDR=nacos-server:8848
      - SECURITY_OAUTH2_RESOURCE-SERVER_JWT_SECRET=your-jwt-secret-key
    ports:
      - "7573:7573"
    depends_on:
      nacos-server:
        condition: service_healthy
      uaa-service:
        condition: service_started
      product-service:
        condition: service_started
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
  ldap-data:
  ldap-config:
  nacos-data:
  nacos-log: